version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 4321:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: db
  backend:
    build: ./todolist
    privileged: true
    ports:
      - 8000:8000
    command:
      bash -c "
      python manage.py migrate &&
      python manage.py fill_base &&
      python manage.py runserver 0.0.0.0:5000
      "
    depends_on:
      - db


      