# Generated by Django 3.2.9 on 2021-11-22 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='devops',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Разработчики'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор заметки'),
        ),
    ]
